# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=600),
        ),
    ]
