# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='user',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
