# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170414_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='file_name',
        ),
    ]
